title: Nordic Love Data Week
nav_title: Nordic Love Data Week<br><small><span class="hide-very-narrow">with</span> Nordic Universities (09-13 February 2026)</small>

event_date: 9–13 Feb 2026
registration_opens_date: Jan 2026
registration_closes_date: 8 Feb 2026

author: Nordic Love Data Week Team
mailbox_address: dinghe@dtu.dk

# Team members
team:
  - name: Sofie Husby
    email: soh.lib@cbs.dk
    image: /assets/Sofie-Husby.jpg
    affiliation: Copenhagen Business School (CBS)
    title: Information Specialist, CBS Library
    links:
      - title: LinkedIn
        url: https://www.linkedin.com/in/sofie-husby-7005273
        icon: bi-linkedin
      - title: ORCID
        url: https://orcid.org/0000-0002-8857-8549
        icon: /assets/orcid.logo.icon.svg
  - name: Rosa Lönneborg
    email: rosa@kth.se
    image: /assets/Rosa-Lonneborg.jpg
    affiliation: KTH Royal Institute of Technology (KTH)
    title: Research Data Coordinator, KTH Library
    links:
      - title: KTH Profile
        url: https://www.kth.se/profile/rosa?l=en
        icon: bi-person-lines-fill
      - title: LinkedIn
        url: https://www.linkedin.com/in/rosalonneborg/
        icon: bi-linkedin
      - title: ORCID
        url: https://orcid.org/0000-0002-7679-1369
        icon: /assets/orcid.logo.icon.svg
  - name: Jitka Stilund Hansen
    email: jstha@dtu.dk
    image: /assets/Jitka-Stilund-Hansen.png
    affiliation: Technical University of Denmark (DTU)
    title: Senior Executive Research Data Management Officer, Office for Research, Advice and Innovation
    links:
      - title: DTU Orbit Profile
        url: https://orbit.dtu.dk/en/persons/jitka-stilund-hansen/
        icon: bi-person-lines-fill
      - title: LinkedIn
        url: https://www.linkedin.com/in/jitkastilundhansen/
        icon: bi-linkedin
      - title: ORCID
        url: https://orcid.org/0000-0002-5888-1221
        icon: /assets/orcid.logo.icon.svg
  - name: Ding He
    email: dinghe@dtu.dk
    image: /assets/Ding-He.png
    affiliation: Technical University of Denmark (DTU)
    title: Research Data Steward, BRIGHT
    links:
      - title: DTU Orbit Profile
        url: https://orbit.dtu.dk/en/persons/ding-he/
        icon: bi-person-lines-fill
      - title: GitHub
        url: https://github.com/dinghe878
        icon: bi-github
      - title: LinkedIn
        url: https://www.linkedin.com/in/ding-he-b9966722/
        icon: bi-linkedin
      - title: ORCID
        url: https://orcid.org/0000-0002-0440-5676
        icon: /assets/orcid.logo.icon.svg
  # Add more team members below:
  # - name: Team Member Name
  #   email: email@example.com
  #   image: /assets/member-name.jpg
  #   affiliation: University Name
  #   title: Position/Title
  #   links:
  #     - title: Profile URL Title
  #       url: https://example.com
  #       icon: bi-person-lines-fill

description:
  Love Data Week is an international celebration of data, taking place every year during the week of Valentine’s day. 
  Universities, nonprofit organizations, government agencies, corporations and individuals are encouraged to host and 
  participate in data-related events and activities.

  This year, for the first time, Nordic Love Data Week is organized by a consortium of Nordic universities, aiming to promote awareness 
  and best practices in research data management, data sharing, and data literacy across the Nordic region.

url: "https://dinhe878.github.io/love-data-week-2026"
baseurl: "/love-data-week-2026"
github_repo: dinhe878/love-data-week-2026

theme: minima

# The actual visibility of the nav bar links is influenced by the event_status
# and registration_status flags below
header_pages:
  - registration.md
  - agenda.md
  - projects.md
  - videos-slides.md
  - resources.md
  - about.md

# Event status
#   soon = event is yet to happen
#    now = event is currently happening
#   over = event has happened
#  (demo = show all pages to demonstrate the template)
event_status: soon

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
# closed = Registration form is now closed
#  (demo = show all pages to demonstrate the template)
registration_status: soon

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/advert.png
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
