title: Nordic Love Data Week
nav_title: Nordic Love Data Week<br><small><span class="hide-very-narrow">with</span> Nordic Universities</small>

event_date: 9–13 Feb 2026
registration_opens_date: 12 Jan 2026
registration_closes_date: 9 Feb 2026

author: Ding He
mailbox_address: dinghe@dtu.dk

# Team members
team:
  - name: Ding He
    email: dinghe@dtu.dk
    image: /assets/Ding-He.png
    affiliation: DTU
    title: Research Data Steward, BRIGHT
    links:
      - title: DTU Orbit Profile
        url: https://orbit.dtu.dk/en/persons/ding-he/
        icon: bi-person-lines-fill
      - title: GitHub
        url: https://github.com/dinghe878
        icon: bi-github
  # Add more team members below:
  # - name: Team Member Name
  #   email: email@example.com
  #   image: /assets/member-name.jpg
  #   affiliation: University Name
  #   title: Position/Title
  #   links:
  #     - title: Profile URL Title
  #       url: https://example.com
  #       icon: bi-person-lines-fill

description:
  Love Data Week is an international celebration of data, taking place every year during the week of Valentine’s day. 
  Universities, nonprofit organizations, government agencies, corporations and individuals are encouraged to host and 
  participate in data-related events and activities.

  This year, for the first time, Nordic Love Data Week is organized by a consortium of Nordic universities, aiming to promote awareness 
  and best practices in research data management, data sharing, and data literacy across the Nordic region.

url: "https://dinhe878.github.io/love-data-week-2026"
baseurl: "/love-data-week-2026"
github_repo: dinhe878/love-data-week-2026

theme: minima

# The actual visibility of the nav bar links is influenced by the event_status
# and registration_status flags below
header_pages:
  - registration.md
  - agenda.md
  - projects.md
  - videos-slides.md
  - resources.md
  - about.md

# Event status
#   soon = event is yet to happen
#    now = event is currently happening
#   over = event has happened
#  (demo = show all pages to demonstrate the template)
event_status: demo

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
# closed = Registration form is now closed
#  (demo = show all pages to demonstrate the template)
registration_status: demo

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/advert.png
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
